services:
  backend:
    build: 
      context : ./backend
      dockerfile: Dockerfile
    image: akashbhardwaj24/muxi-backend
  
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: akashbhardwaj24/muxi-frontend
