name: Continous Deployment
on:
  push:
    branches: [main]

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Create env
        run : |
          echo "NEXT_PUBLIC_APIKEY=${{ secrets.NEXT_PUBLIC_APIKEY }}" > ./frontend/.env
          echo "NEXT_PUBLIC_AUTHDOMAIN=${{ secrets.NEXT_PUBLIC_AUTHDOMAIN }}" >> ./frontend/.env
          echo "NEXT_PUBLIC_PROJECTID=${{ secrets.NEXT_PUBLIC_PROJECTID }}" > ./frontend/.env
          echo "NEXT_PUBLIC_DATABASE_URL=${{ secrets.NEXT_PUBLIC_DATABASE_URL }}" >> ./frontend/.env
          echo "NEXT_PUBLIC_STORAGEBUCKET=${{ secrets.NEXT_PUBLIC_STORAGEBUCKET }}" > ./frontend/.env
          echo "NEXT_PUBLIC_MESSAGESENDERID=${{ secrets.NEXT_PUBLIC_MESSAGESENDERID }}" >> ./frontend/.env
          echo "NEXT_PUBLIC_APPID=${{ secrets.NEXT_PUBLIC_APPID }}" >> ./frontend/.env


      - name: Docker Login
        uses : docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}


      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v2

      - name: Build The frontend docker file
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: akashbhardwaj24/muxi-frontend:${{ github.sha }}

      - name: Build the backend docker file
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: akashbhardwaj24/muxi-backend:${{ github.sha }}
      
      - name: Clone the Ops Repo
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/akashbhardwaj23/ops.git
          cd ops
          sed -i 's|image: akashbhardwaj24/muxi-frontend:.*|image: akashbhardwaj24/muxi-frontend:${{ github.sha }}|' staging/muxi/deployment.yml
          sed -i 's|image: akashbhardwaj24/muxi-backend:.*|image: akashbhardwaj24/muxi-backend:${{github.sha}}|' staging/muxi/deployment.yml
          git config user.name "Github Actions Bot"
          git config user.email "github@actions.com"
          git add staging/muxi/deployment.yml
          git commit -m "Updated muxi images to ${{ github.sha }}"
          git push https://${PAT}@github.com/akashbhardwaj23/ops.git main
